use anyhow::Result;

use crate::git::format_duration;
use crate::models::{Freshness, RepoSummary, Repository};
use super::Reporter;

pub struct MarkdownReporter;

impl MarkdownReporter {
    pub fn new() -> Self {
        Self
    }
}

impl Reporter for MarkdownReporter {
    fn generate(&self, repos: &[Repository], summary: &RepoSummary) -> Result<String> {
        let mut md = String::new();
        let now = chrono::Local::now().format("%Y-%m-%d %H:%M:%S");

        // Title
        md.push_str("# 📦 GetLatestRepo Scan Report\n\n");
        md.push_str(&format!("Generated at: {}\n\n", now));

        // Summary
        md.push_str("## 📊 Summary\n\n");
        md.push_str(&format!("- **TotalRepository**: {}\n", summary.total));
        md.push_str(&format!("- 🔴 Need updates: {}\n", summary.has_updates));
        md.push_str(&format!("- 🟢 Synced: {}\n", summary.synced));
        md.push_str(&format!("- 🟡 Local changes: {}\n", summary.dirty));
        md.push_str(&format!("- ⚫ Remote unreachable: {}\n", summary.unreachable));
        md.push_str(&format!("- ⚪ No remote branch: {}\n", summary.no_remote));
        md.push('\n');

        // Repository list
        if !repos.is_empty() {
            md.push_str("## 📋 Repository Details\n\n");
            md.push_str("| Repository | Branch | Status | Behind | Local changes | Last update |\n");
            md.push_str("|------|------|------|--------|----------|----------|\n");

            for repo in repos {
                let status = match repo.freshness {
                    Freshness::HasUpdates => "🔴 Need updates",
                    Freshness::Synced => "🟢 Synced",
                    Freshness::Unreachable => "⚫ Unreachable",
                    Freshness::NoRemote => "⚪ No remote",
                };

                let dirty_mark = if repo.dirty { "📝 Yes" } else { "-" };
                let behind = if repo.behind_count > 0 {
                    format!("{} commits", repo.behind_count)
                } else {
                    "-".to_string()
                };

                md.push_str(&format!(
                    "| {} | {} | {} | {} | {} | {} |\n",
                    repo.name,
                    repo.branch.as_deref().unwrap_or("-"),
                    status,
                    behind,
                    dirty_mark,
                    format_duration(&repo.last_commit_at)
                ));
            }

            md.push('\n');
        }

        // Repositories needing attention
        let needs_attention: Vec<_> = repos.iter()
            .filter(|r| r.freshness == Freshness::HasUpdates || r.dirty)
            .collect();

        if !needs_attention.is_empty() {
            md.push_str("## ⚠️ Repositories needing attention\n\n");
            
            for repo in needs_attention {
                md.push_str(&format!("### {}\n\n", repo.name));
                md.push_str(&format!("- **path**: `{}`\n", repo.path));
                md.push_str(&format!("- **Branch**: `{}`\n", 
                    repo.branch.as_deref().unwrap_or("N/A")));
                
                if repo.freshness == Freshness::HasUpdates {
                    md.push_str(&format!("- **Behind**: {} commits\n", repo.behind_count));
                }
                
                if repo.dirty {
                    md.push_str(&format!("- **Local changes**: {} files\n", repo.dirty_files.len()));
                    md.push_str("- **Changed files**:\n");
                    for file in &repo.dirty_files {
                        md.push_str(&format!("  - `{}`\n", file));
                    }
                }

                if let Some(ref msg) = repo.last_commit_message {
                    md.push_str(&format!("- **Last commit**: {}\n", msg.trim()));
                }

                md.push('\n');
            }
        }

        // Footer
        md.push_str("---\n\n");
        md.push_str("*Generated by [GetLatestRepo](https://github.com/xcjy8/GetLatestRepo)*\n");

        Ok(md)
    }

    fn extension(&self) -> &'static str {
        "md"
    }
}
