use clap::{Parser, Subcommand, ValueEnum};
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "getlatestrepo")]
#[command(about = "A fast and elegant local Git repository manager")]
#[command(version)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,
    
    /// Disable security scan before fetch/pull
    #[arg(long, global = true)]
    pub no_security_check: bool,

    /// 自动跳过高风险仓库（不交互确认，直接跳过）
    #[arg(long, global = true)]
    pub auto_skip_high_risk: bool,
    
    /// Enable proxy (default: http://127.0.0.1:7890)
    #[arg(long, global = true)]
    pub proxy: bool,
    
    /// Custom proxy address (e.g. http://127.0.0.1:1080)
    #[arg(long, global = true, value_name = "URL")]
    pub proxy_url: Option<String>,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Initialize config, specify the folder to manage
    Init {
        /// Root directory path
        path: PathBuf,
    },

    /// Scan repositories and generate report
    Scan {
        /// Run fetch before scanning
        #[arg(long)]
        fetch: bool,

        /// Output format
        #[arg(short, long, value_enum, default_value = "terminal")]
        output: OutputFormat,

        /// Output file path (auto-generated by default)
        #[arg(short, long)]
        out: Option<PathBuf>,

        /// Limit scan depth
        #[arg(short, long)]
        depth: Option<usize>,

        /// Concurrency (default: 5)
        #[arg(short, long, default_value = "5")]
        jobs: usize,
    },

    /// Fetch all repositories
    Fetch {
        /// Concurrency (default: 5)
        #[arg(short, long, default_value = "5")]
        jobs: usize,

        /// Timeout in seconds (default: 30)
        #[arg(short, long, default_value = "30")]
        timeout: u64,
    },

    /// View a single repository's details
    Status {
        /// Repository path (ignored when --issues is set)
        path: PathBuf,

        /// Show diff
        #[arg(long)]
        diff: bool,

        /// Show all repositories with issues (needauth, unreachable, dirty+behind, missing)
        #[arg(long)]
        issues: bool,
    },

    /// Configuration management
    Config {
        #[command(subcommand)]
        command: ConfigCommands,
    },

    /// Execute a preset workflow
    Workflow {
        /// Workflow name (daily/check/report/ci/pull-safe/pull-force/pull-backup)
        name: Option<String>,

        /// List all available workflows
        #[arg(long)]
        list: bool,

        /// Show execution plan only, do not execute
        #[arg(long)]
        dry_run: bool,

        /// Silent mode (returns only exit code)
        #[arg(long)]
        silent: bool,

        /// Concurrency (overrides workflow default)
        #[arg(short, long)]
        jobs: Option<usize>,

        /// Timeout in seconds (overrides workflow default)
        #[arg(short, long)]
        timeout: Option<u64>,

        /// Show diff after pull (only effective for pull-safe/pull-force)
        #[arg(long)]
        diff_after: bool,

        /// Auto-confirm (skip Y/n prompt, only for pull-safe)
        #[arg(long)]
        yes: bool,
        
        /// Disable pull safety check (repo-deletion detection)
        /// Warning: disabling this may cause local code loss due to remote repo deletion!
        #[arg(long)]
        no_pull_guard: bool,
    },

    /// Discard local changes
    Discard {
        /// Repository path (shows list to choose if not provided)
        path: Option<String>,

        /// Auto-confirm (skip Y/n prompt)
        #[arg(long)]
        yes: bool,
    },
}

#[derive(Subcommand)]
pub enum ConfigCommands {
    /// Add scan path
    Add {
        path: PathBuf,
    },
    
    /// List all configurations
    List,
    
    /// Remove scan path
    Remove {
        /// Path or ID
        path_or_id: String,
    },
    
    /// Set ignore rules (comma-separated)
    Ignore {
        patterns: String,
    },
    
    /// Show config storage location
    Path,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum OutputFormat {
    /// Terminal table (default)
    Terminal,
    /// HTML report
    Html,
    /// Markdown report
    Markdown,
}

impl OutputFormat {
    /// Get file extension for output format
    /// 
    /// Currently unused, reserved for future report export functionality
    #[allow(dead_code)]
    pub fn extension(&self) -> &'static str {
        match self {
            OutputFormat::Terminal => "txt",
            OutputFormat::Html => "html",
            OutputFormat::Markdown => "md",
        }
    }
}
